name: "Code Vulnerability Scan"
description: "GKE Login and helm setup"
inputs:
  googleCredentials:
    description: "Google credentials"
    required: true
  clusterName:
    description: "Name of the cluster"
    required: true
  location:
    description: "Location of the cluster"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.googleCredentials }}

    - name: get-credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ inputs.clusterName }}
        location: ${{ inputs.location }}

    - name: Helm download
      id: helmDownload
      run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      shell: bash
