name: build-container
on: 
  workflow_call:
    inputs:
      crName:
        required: true
        type: string
      codeQlScan:
        required: false
        type: boolean
        default: true
      
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      SNYK_TOKEN:
        required: true
      SYSDIG_SECURE_TOKEN:
        required: true
  
permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
      checks: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      if: ${{ inputs.codeQlScan == true }}
      with:
        languages: go

    - name: Perform CodeQL Analysis
      if: ${{ inputs.codeQlScan == true }}
      uses: github/codeql-action/analyze@v2

    #https://github.com/docker/login-action
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Calculate tag
      run: |
        branchName="$(git rev-parse --abbrev-ref HEAD)"
        commitId="$(git rev-parse --short HEAD)"
        repoName="$(basename `git rev-parse --show-toplevel`)"

        if [[ ${branchName} == main ]] ; then
          prefix=M
        else
          prefix=F-$(echo $branchName | cut -f 2 -d/)
        fi

        tag="$repoName:$prefix-$(date '+%Y%m%d')-$commitId"
        echo "TAG=$(echo $tag)" >> $GITHUB_ENV

    - name: Build
      run: docker build container/expetra/ -t ${{ inputs.crName }}/${{ env.TAG}}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@d63413b0a4a4482237085319f7f4a1ce99a8f2ac
      with:
        image-ref: '${{ inputs.crName }}/${{ env.TAG}}'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@e0bb9436303033a6ecc7f3d3af5e842c269a969d
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{ inputs.crName }}/${{ env.TAG}}
        args: --file=container/expetra/Dockerfile

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif

    - name: Sysdig Secure Inline Scan
      id: scan
      uses: sysdiglabs/scan-action@0e483c3a8ed88a6d7394a1baaf0e432db09f240f
      with:
        image-tag: ${{ inputs.crName }}/${{ env.TAG}}
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN}}
        sysdig-secure-url: https://eu1.app.sysdig.com 
        dockerfile-path: container/expetra/Dockerfile
        input-type: docker-daemon
        ignore-failed-scan: true
        run-as-user: root

    - uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: ${{ steps.scan.outputs.sarifReport }}

    - name: Push
      if: ${{ github.event_name != 'schedule' }}
      run: docker push ${{ inputs.crName }}/${{ env.TAG }}
